SUPABASE_URL = "https://vsvwfpncckabwkjqchwj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdndmcG5jY2thYndranFjaHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3NDI1OTYsImV4cCI6MjA5NTMxODU5Nn0.pcE8TF-2QbkhAtrY8r3mldCWQFFA4DL46OTOpnYeVok"

ADMIN_USER = "admin"

PREDICTION_LOCK_GROUPS_AT = "2026-06-10 23:59:59"
PREDICTION_LOCK_R32_AT = "2026-06-27 23:59:59"
PREDICTION_LOCK_R16_AT = "2026-07-03 23:59:59"
PREDICTION_LOCK_QUARTERS_AT = "2026-07-08 23:59:59"
PREDICTION_LOCK_SEMIS_AT = "2026-07-13 23:59:59"
PREDICTION_LOCK_THIRD_PLACE_AT = "2026-07-17 23:59:59"
PREDICTION_LOCK_FINAL_AT = "2026-07-18 23:59:59"
PREDICTION_LOCK_EXTRAS_AT = "2026-06-10 23:59:59"