SUPABASE_URL = "https://vsvwfpncckabwkjqchwj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdndmcG5jY2thYndranFjaHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3NDI1OTYsImV4cCI6MjA5NTMxODU5Nn0.pcE8TF-2QbkhAtrY8r3mldCWQFFA4DL46OTOpnYeVok"
ADMIN_USER = "admin"